name: helpooappclient
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.3+177

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.6
  audioplayers: ^5.0.0
  bloc: ^8.1.2
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  dartz: ^0.10.1
  dio: ^5.0.1
  easy_localization: ^3.0.0
  encrypt: ^5.0.1
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  firebase_analytics: ^10.10.2
  firebase_messaging: ^14.8.2
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^13.0.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  uni_links: ^0.5.1
  geocoding: ^2.0.4
  geolocator: ^10.1.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.18
  hexcolor: ^3.0.1
  hive: ^2.2.3
  image_picker: ^1.0.1
  intl: ^0.19.0
  logger: ^2.0.1
  map_picker: ^0.0.3
  maps_launcher: ^2.2.0
  package_info_plus: ^4.0.2
  permission_handler: ^10.0.0
  requests_inspector: ^3.3.2
  record: ^4.4.4
  shared_preferences: ^2.1.1
  shimmer: ^2.0.0
  simple_animations: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.1
  step_progress_indicator: ^1.0.2
  supercharged: ^2.1.1
  syncfusion_flutter_pdfviewer: ^21.1.38
  url_launcher: ^6.1.6
  webview_flutter: ^4.0.7
  lottie: ^2.6.0
  flashy_tab_bar2: 0.0.5
  searchfield: ^0.8.6
  pinput: ^3.0.1
  pdf: ^3.10.6
  share_extend: ^2.0.0
  location: ^5.0.3
  device_preview: ^1.2.0
  uuid: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/report/
    - assets/translations/
    - assets/json/
    - assets/fonts/
    - assets/fonts/cairo/
    - assets/fonts/tajawal/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
