// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - fuchsia - linux - windows'
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXFT2dpi2TSRgzpcpTFX68AepKjiEibI',
    appId: '1:127242797918:web:bf2fcc4790b72721af05cf',
    messagingSenderId: '127242797918',
    projectId: 'helpoo-4f9cf',
    authDomain: 'helpoo-4f9cf.firebaseapp.com',
    storageBucket: 'helpoo-4f9cf.appspot.com',
    measurementId: 'G-EEEHE83KXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjhHH8sk2saaFkDqtKEZJ7j3G-ylnP_g',
    appId: '1:8691102844:android:25dcfe17da736509c045f9',
    messagingSenderId: '8691102844',
    projectId: 'valiant-carrier-337111',
    storageBucket: 'valiant-carrier-337111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk-oaNMMX6uyMSr06eXHHa-rGAEQerKUQ',
    appId: '1:8691102844:ios:6b1e6f1996dc2133c045f9',
    messagingSenderId: '8691102844',
    projectId: 'valiant-carrier-337111',
    storageBucket: 'valiant-carrier-337111.appspot.com',
    iosBundleId: 'com.helpoo.app',
  );

}